---
- name: launch all the things
  hosts: localhost
  roles:
    - instances

- name: install webserver
  hosts: web-server
  become_user: root
  roles:
    - webserver

- name: install mariadb
  hosts: mysql-db
  roles:
    - mysql

- name: install varnish
  hosts: varnish-cache
  roles:
    - varnish

- name: install nginx
  hosts: nginx
  roles:
    - nginx
