---
- replace:
    dest: /etc/varnish/varnish.params
    regexp: 'VARNISH_LISTEN_PORT=6081'
    replace: "VARNISH_LISTEN_PORT={{ varnish_port }}"

- name: restart varnish
  service: name=varnish state=restarted

- name: Open port varnish
  firewalld: zone=public port={{ varnish_port }}/tcp permanent=yes state=enabled
  notify: restart firewalld
