---
- name: launch instance
  register: varnishCache
  os_server:
    state: present
    name: varnish-cache
    image: c922a7d0-cac5-4913-9b73-1ef84ae7ab2b
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: gp1.subsonic
    meta:
      hostname: varnish-cache
      group: varnish

- add_host:
    name: varnish-cache
    groups: varnish-cache
    ansible_host: "{{varnishCache.server.public_v4}}"
    ansible_user: centos
    ansible_become: true

- name: wait for ssh
  local_action: wait_for
    port=22
    host="{{varnishCache.server.public_v4}}"
    delay=10

- pause:
    seconds: 20
