---
- name: launch instance
  register: webServer
  os_server:
    state: present
    name: web-server
    image: f84868a5-5261-404a-9c54-ec317ea16b94
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: gp1.subsonic
    meta:
      hostname: web-server
      group: webserver

- add_host:
    name: web-server
    groups: web-server
    ansible_host: "{{webServer.server.public_v4}}"
    ansible_user: centos
    ansible_become: true

- name: wait for ssh
  local_action: wait_for
    port=22
    host="{{webServer.server.public_v4}}"
    delay=10

- pause:
    seconds: 20
