---
- lineinfile:
    dest: /etc/my.cnf
    insertafter: '(\[mysqld\])'
    line: "bind-address = {{ ansible_host }}"
    state: present

- name: restart mysql
  service: name=mariadb state=restarted
