---
#- name: Delete anonymous users for ansible
#  mysql_user: name="" host="{{ ansible_hostname }}" state="absent"

#DELETE FROM mysql.db WHERE db LIKE 'tes%' AND user='';
#FLUSH PRIVILEGES;

- name: Delete anonymous users
  mysql_user: name="" host_all="yes" state="absent"

- name: Delete root user with ansible hostname
  mysql_user: user="root" host="{{ ansible_hostname }}" state="absent"

- name: Remove test database
  mysql_db: name=test state=absent

- name: Delete mysql-db.novalocal root user
  mysql_user: user="root" host="mysql-db.novalocal" state="absent"

- name: Set MySQL Root Password
  mysql_user: user=root host={{ item }} password="{{ randpassroot.stdout }}" priv=*.*:ALL,GRANT state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template:
    src: roles/mysql/templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
