---
- name: Install Packages
  yum: name={{ item }}
  with_items:
        - httpd
        - php
        - php-mysql
        - php-gd
        - python-dateutil
        - unzip
        - firewalld
        - MySQL-python
        - mysql

- name: Start Apache
  service: name=httpd state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: Open port for varnish to access
  firewalld: zone=public port={{ webserver_port }}/tcp permanent=yes state=enabled
  notify: restart firewalld
